apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-node2
  labels:
    app: flask-node2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-node2
      node: node2  # Eindeutiger Name
  template:
    metadata:
      labels:
        app: flask-node2
        node: node2
    spec:
      containers:
        - name: flask-node2
          image: stu240498/oldflask-node  # Dein Docker-Image hier einfügen
          ports:
            - containerPort: 5000
          env:
            - name: NAME
              value: "node2"  # Name des Nodes
            - name: FLASK_PORT
              value: "5001"  # Port für Flask
