apiVersion: v1
kind: Service
metadata:
  name: flask-node2-service
spec:
  type: NodePort  # Ermöglicht Zugriff von außerhalb des Clusters
  selector:
    app: flask-node2
    node: node2  # Service für diesen speziellen Node
  ports:
    - protocol: TCP
      port: 5001  # Port für den Zugriff von außen (geht nicht)
      targetPort: 5001  # Port im Container
      nodePort: 30002  # Port auf dem Host (30001-32767 erlaubt)
