apiVersion: v1
kind: Service
metadata:
  name: flask-node1-service
spec:
  type: NodePort  # Ermöglicht Zugriff von außerhalb des Clusters
  selector:
    app: flask-node
    node: node1  # Service für diesen speziellen Node
  ports:
    - protocol: TCP
      port: 5000  # Port für den Zugriff von außen (geht nicht)
      targetPort: 5000  # Port im Container
      nodePort: 30001  # Port auf dem Host (30001-32767 erlaubt)
