apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure-f-finalized
  namespace: bpi
spec:
  action: pod-failure
  mode: one
  duration: '86400'
  selector:
    labelSelectors:
      app: a-finalized