apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: delay-b
spec:
  action: delay
  mode: one
  selector:
    namespaces:
      - edge-network
    labelSelectors:
      'app': 'flask-node-b'
  delay:
    latency: '2s'
    correlation: '100'
    jitter: '0ms'