apiVersion: chaos-mesh.org/v1alpha1
kind: HTTPChaos
metadata:
  name: test-http-chaos
spec:
  mode: all
  selector:
    labelSelectors:
      app: flask-node-b
  target: Request
  port: 30011
  method: GET
  path: /footprint_matrix
  abort: true
  duration: 5m
