apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: packet-loss-b
spec:
  action: loss
  mode: one
  selector:
    namespaces:
      - edge-network
    labelSelectors:
      'app': 'flask-node-b'
  loss:
    loss: "50"     # Prozentualer Paketverlust (z. B. 50%)
    correlation: "0"  # Kein Zusammenhang zwischen Verlusten
