apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: bpi
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
  namespace: bpi
subjects:
  - kind: ServiceAccount
    name: default  # Verwendeter ServiceAccount im Deployment
    namespace: bpi
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
