apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure-central-node-b
  namespace: central-network
spec:
  action: pod-failure
  mode: one
  duration: '100s'
  selector:
    labelSelectors:
      app: worker-node-b