apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-node-a
  namespace: edge-network
spec:
  replicas: 1  # Anzahl der Pods
  selector:
    matchLabels:
      app: flask-node-a
  template:
    metadata:
      labels:
        app: flask-node-a
    spec:
      containers:
        - name: flask-node-a
          image: stu240498/flask-node
          ports:
            - containerPort: 5000
          env:
            - name: NAME
              value: "a"  # NAME f端r den ersten Pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-node-b
  namespace: edge-network
spec:
  replicas: 2  # Anzahl der Pods
  selector:
    matchLabels:
      app: flask-node-b
  template:
    metadata:
      labels:
        app: flask-node-b
    spec:
      containers:
        - name: flask-node-b
          image: stu240498/flask-node
          ports:
            - containerPort: 5000
          env:
            - name: NAME
              value: "b"  # NAME f端r den zweiten Pod
          readinessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-node-c
  namespace: edge-network
spec:
  replicas: 1  # Anzahl der Pods
  selector:
    matchLabels:
      app: flask-node-c
  template:
    metadata:
      labels:
        app: flask-node-c
    spec:
      containers:
        - name: flask-node-c
          image: stu240498/flask-node
          ports:
            - containerPort: 5000
          env:
            - name: NAME
              value: "c"  # NAME f端r den dritten Pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-node-d
  namespace: edge-network
spec:
  replicas: 1  # Anzahl der Pods
  selector:
    matchLabels:
      app: flask-node-d
  template:
    metadata:
      labels:
        app: flask-node-d
    spec:
      containers:
        - name: flask-node-d
          image: stu240498/flask-node
          ports:
            - containerPort: 5000
          env:
            - name: NAME
              value: "d"  # NAME f端r den dritten Pod
